error:
  ok: 200
  # 通用错误码
  200: "请求成功"
  1000: "未知错误"
  1001: "请求参数错误"
  1006: "token 不存在或已过期"
  # 服务级错误码
  10001: "参数有误"
  10002: "签名参数有误"
  # 模块级错误码 - 会议室预订模块
  20101: "验证地点名称失败"
  20102: "地点名称重复"
  20103: "地点不存在或已删除"
  20104: "验证设备名称失败"
  20105: "设备名称重复"
  20106: "设备不存在或已删除"
  20107: "验证会议室名称失败"
  20108: "会议室名称重复"
  20109: "会议室不存在或已删除"
  20110: "会议室时间重复"
  20111: "会议不存在或已删除"
  20112: "地点下已添加会议室不能删除"
  20113: "会议室存在预约不能删除"
  30105: "邀请人不存在或已删除"

  # 模块级错误码 - 用户模块
  30100: "用户服务异常"
  30101: "用户手机号不合法"
  30102: "用户验证码有误"
  30103: "此用户不存在，请核实后登录"
  30104: "用户已被禁用"





