// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/notice/notice.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for NoticeService service

func NewNoticeServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for NoticeService service

type NoticeService interface {
	GetNotices(ctx context.Context, in *ReqGetNotices, opts ...client.CallOption) (*Response, error)
	CreateNotice(ctx context.Context, in *ReqNoticeCreate, opts ...client.CallOption) (*Response, error)
}

type noticeService struct {
	c    client.Client
	name string
}

func NewNoticeService(name string, c client.Client) NoticeService {
	return &noticeService{
		c:    c,
		name: name,
	}
}

func (c *noticeService) GetNotices(ctx context.Context, in *ReqGetNotices, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "NoticeService.GetNotices", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeService) CreateNotice(ctx context.Context, in *ReqNoticeCreate, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "NoticeService.CreateNotice", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NoticeService service

type NoticeServiceHandler interface {
	GetNotices(context.Context, *ReqGetNotices, *Response) error
	CreateNotice(context.Context, *ReqNoticeCreate, *Response) error
}

func RegisterNoticeServiceHandler(s server.Server, hdlr NoticeServiceHandler, opts ...server.HandlerOption) error {
	type noticeService interface {
		GetNotices(ctx context.Context, in *ReqGetNotices, out *Response) error
		CreateNotice(ctx context.Context, in *ReqNoticeCreate, out *Response) error
	}
	type NoticeService struct {
		noticeService
	}
	h := &noticeServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&NoticeService{h}, opts...))
}

type noticeServiceHandler struct {
	NoticeServiceHandler
}

func (h *noticeServiceHandler) GetNotices(ctx context.Context, in *ReqGetNotices, out *Response) error {
	return h.NoticeServiceHandler.GetNotices(ctx, in, out)
}

func (h *noticeServiceHandler) CreateNotice(ctx context.Context, in *ReqNoticeCreate, out *Response) error {
	return h.NoticeServiceHandler.CreateNotice(ctx, in, out)
}
