// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/meeting/room.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SpaceId int64  `protobuf:"varint,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"` //所属地点ID
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                       //会议室名称
	// Types that are assignable to OneStatus:
	//	*Room_Status
	OneStatus   isRoom_OneStatus `protobuf_oneof:"one_status"`
	ImageUrl    string           `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`           //会议室图片
	CapacityMin int64            `protobuf:"varint,6,opt,name=capacity_min,json=capacityMin,proto3" json:"capacity_min,omitempty"` //建议使用人数（最小）
	CapacityMax int64            `protobuf:"varint,7,opt,name=capacity_max,json=capacityMax,proto3" json:"capacity_max,omitempty"` //建议使用人数（最大）
	CreatedAt   string           `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meeting_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meeting_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_proto_meeting_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Room) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *Room) GetOneStatus() isRoom_OneStatus {
	if m != nil {
		return m.OneStatus
	}
	return nil
}

func (x *Room) GetStatus() string {
	if x, ok := x.GetOneStatus().(*Room_Status); ok {
		return x.Status
	}
	return ""
}

func (x *Room) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Room) GetCapacityMin() int64 {
	if x != nil {
		return x.CapacityMin
	}
	return 0
}

func (x *Room) GetCapacityMax() int64 {
	if x != nil {
		return x.CapacityMax
	}
	return 0
}

func (x *Room) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type isRoom_OneStatus interface {
	isRoom_OneStatus()
}

type Room_Status struct {
	Status string `protobuf:"bytes,4,opt,name=status,proto3,oneof"` // 启用状态：0禁用、1启用
}

func (*Room_Status) isRoom_OneStatus() {}

type ReqGetRooms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int64  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SortBy   string `protobuf:"bytes,3,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	Order    string `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	SpaceId  int64  `protobuf:"varint,5,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Name     string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to OneStatus:
	//	*ReqGetRooms_Status
	OneStatus isReqGetRooms_OneStatus `protobuf_oneof:"one_status"`
}

func (x *ReqGetRooms) Reset() {
	*x = ReqGetRooms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meeting_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetRooms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetRooms) ProtoMessage() {}

func (x *ReqGetRooms) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meeting_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetRooms.ProtoReflect.Descriptor instead.
func (*ReqGetRooms) Descriptor() ([]byte, []int) {
	return file_proto_meeting_room_proto_rawDescGZIP(), []int{1}
}

func (x *ReqGetRooms) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ReqGetRooms) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ReqGetRooms) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ReqGetRooms) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *ReqGetRooms) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *ReqGetRooms) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *ReqGetRooms) GetOneStatus() isReqGetRooms_OneStatus {
	if m != nil {
		return m.OneStatus
	}
	return nil
}

func (x *ReqGetRooms) GetStatus() string {
	if x, ok := x.GetOneStatus().(*ReqGetRooms_Status); ok {
		return x.Status
	}
	return ""
}

type isReqGetRooms_OneStatus interface {
	isReqGetRooms_OneStatus()
}

type ReqGetRooms_Status struct {
	Status string `protobuf:"bytes,7,opt,name=status,proto3,oneof"`
}

func (*ReqGetRooms_Status) isReqGetRooms_OneStatus() {}

type ReqGetRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReqGetRoom) Reset() {
	*x = ReqGetRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meeting_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetRoom) ProtoMessage() {}

func (x *ReqGetRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meeting_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetRoom.ProtoReflect.Descriptor instead.
func (*ReqGetRoom) Descriptor() ([]byte, []int) {
	return file_proto_meeting_room_proto_rawDescGZIP(), []int{2}
}

func (x *ReqGetRoom) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReqCreateRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceId int64  `protobuf:"varint,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to OneStatus:
	//	*ReqCreateRoom_Status
	OneStatus   isReqCreateRoom_OneStatus `protobuf_oneof:"one_status"`
	ImageUrl    string                    `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CapacityMin int64                     `protobuf:"varint,6,opt,name=capacity_min,json=capacityMin,proto3" json:"capacity_min,omitempty"`
	CapacityMax int64                     `protobuf:"varint,7,opt,name=capacity_max,json=capacityMax,proto3" json:"capacity_max,omitempty"`
	DeviceIds   string                    `protobuf:"bytes,8,opt,name=DeviceIds,proto3" json:"DeviceIds,omitempty"`
}

func (x *ReqCreateRoom) Reset() {
	*x = ReqCreateRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meeting_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqCreateRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCreateRoom) ProtoMessage() {}

func (x *ReqCreateRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meeting_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCreateRoom.ProtoReflect.Descriptor instead.
func (*ReqCreateRoom) Descriptor() ([]byte, []int) {
	return file_proto_meeting_room_proto_rawDescGZIP(), []int{3}
}

func (x *ReqCreateRoom) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *ReqCreateRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *ReqCreateRoom) GetOneStatus() isReqCreateRoom_OneStatus {
	if m != nil {
		return m.OneStatus
	}
	return nil
}

func (x *ReqCreateRoom) GetStatus() string {
	if x, ok := x.GetOneStatus().(*ReqCreateRoom_Status); ok {
		return x.Status
	}
	return ""
}

func (x *ReqCreateRoom) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ReqCreateRoom) GetCapacityMin() int64 {
	if x != nil {
		return x.CapacityMin
	}
	return 0
}

func (x *ReqCreateRoom) GetCapacityMax() int64 {
	if x != nil {
		return x.CapacityMax
	}
	return 0
}

func (x *ReqCreateRoom) GetDeviceIds() string {
	if x != nil {
		return x.DeviceIds
	}
	return ""
}

type isReqCreateRoom_OneStatus interface {
	isReqCreateRoom_OneStatus()
}

type ReqCreateRoom_Status struct {
	Status string `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

func (*ReqCreateRoom_Status) isReqCreateRoom_OneStatus() {}

type ReqUpdateRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SpaceId int64  `protobuf:"varint,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to OneStatus:
	//	*ReqUpdateRoom_Status
	OneStatus   isReqUpdateRoom_OneStatus `protobuf_oneof:"one_status"`
	ImageUrl    string                    `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CapacityMin int64                     `protobuf:"varint,6,opt,name=capacity_min,json=capacityMin,proto3" json:"capacity_min,omitempty"`
	CapacityMax int64                     `protobuf:"varint,7,opt,name=capacity_max,json=capacityMax,proto3" json:"capacity_max,omitempty"`
	DeviceIds   string                    `protobuf:"bytes,8,opt,name=DeviceIds,proto3" json:"DeviceIds,omitempty"`
}

func (x *ReqUpdateRoom) Reset() {
	*x = ReqUpdateRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meeting_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUpdateRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdateRoom) ProtoMessage() {}

func (x *ReqUpdateRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meeting_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpdateRoom.ProtoReflect.Descriptor instead.
func (*ReqUpdateRoom) Descriptor() ([]byte, []int) {
	return file_proto_meeting_room_proto_rawDescGZIP(), []int{4}
}

func (x *ReqUpdateRoom) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReqUpdateRoom) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *ReqUpdateRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *ReqUpdateRoom) GetOneStatus() isReqUpdateRoom_OneStatus {
	if m != nil {
		return m.OneStatus
	}
	return nil
}

func (x *ReqUpdateRoom) GetStatus() string {
	if x, ok := x.GetOneStatus().(*ReqUpdateRoom_Status); ok {
		return x.Status
	}
	return ""
}

func (x *ReqUpdateRoom) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ReqUpdateRoom) GetCapacityMin() int64 {
	if x != nil {
		return x.CapacityMin
	}
	return 0
}

func (x *ReqUpdateRoom) GetCapacityMax() int64 {
	if x != nil {
		return x.CapacityMax
	}
	return 0
}

func (x *ReqUpdateRoom) GetDeviceIds() string {
	if x != nil {
		return x.DeviceIds
	}
	return ""
}

type isReqUpdateRoom_OneStatus interface {
	isReqUpdateRoom_OneStatus()
}

type ReqUpdateRoom_Status struct {
	Status string `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

func (*ReqUpdateRoom_Status) isReqUpdateRoom_OneStatus() {}

type ReqDeleteRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReqDeleteRoom) Reset() {
	*x = ReqDeleteRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_meeting_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqDeleteRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDeleteRoom) ProtoMessage() {}

func (x *ReqDeleteRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_meeting_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDeleteRoom.ProtoReflect.Descriptor instead.
func (*ReqDeleteRoom) Descriptor() ([]byte, []int) {
	return file_proto_meeting_room_proto_rawDescGZIP(), []int{5}
}

func (x *ReqDeleteRoom) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_meeting_room_proto protoreflect.FileDescriptor

var file_proto_meeting_room_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2f,
	0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x1a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xef, 0x01, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72,
	0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x6d, 0x69,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x4d, 0x69, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x5f, 0x6d, 0x61, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x61, 0x70, 0x61,
	0x63, 0x69, 0x74, 0x79, 0x4d, 0x61, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x0c, 0x0a, 0x0a, 0x6f, 0x6e, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0xc2, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0c, 0x0a, 0x0a, 0x6f,
	0x6e, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1c, 0x0a, 0x0a, 0x52, 0x65, 0x71,
	0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xe7, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x6d, 0x69, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x4d,
	0x69, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x6d,
	0x61, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69,
	0x74, 0x79, 0x4d, 0x61, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x64, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x73, 0x42, 0x0c, 0x0a, 0x0a, 0x6f, 0x6e, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0xf7, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x70,
	0x61, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x4d, 0x69, 0x6e, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x4d, 0x61, 0x78, 0x12,
	0x1c, 0x0a, 0x09, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x73, 0x42, 0x0c, 0x0a,
	0x0a, 0x6f, 0x6e, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1f, 0x0a, 0x0d, 0x52,
	0x65, 0x71, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0xaf, 0x02, 0x0a,
	0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x14, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x1a, 0x12,
	0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12,
	0x13, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x1a, 0x12, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x1a, 0x12, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52,
	0x65, 0x71, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x1a, 0x12, 0x2e, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x12, 0x16, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x1a, 0x12, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_meeting_room_proto_rawDescOnce sync.Once
	file_proto_meeting_room_proto_rawDescData = file_proto_meeting_room_proto_rawDesc
)

func file_proto_meeting_room_proto_rawDescGZIP() []byte {
	file_proto_meeting_room_proto_rawDescOnce.Do(func() {
		file_proto_meeting_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_meeting_room_proto_rawDescData)
	})
	return file_proto_meeting_room_proto_rawDescData
}

var file_proto_meeting_room_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_meeting_room_proto_goTypes = []interface{}{
	(*Room)(nil),          // 0: meeting.Room
	(*ReqGetRooms)(nil),   // 1: meeting.ReqGetRooms
	(*ReqGetRoom)(nil),    // 2: meeting.ReqGetRoom
	(*ReqCreateRoom)(nil), // 3: meeting.ReqCreateRoom
	(*ReqUpdateRoom)(nil), // 4: meeting.ReqUpdateRoom
	(*ReqDeleteRoom)(nil), // 5: meeting.ReqDeleteRoom
	(*Response)(nil),      // 6: response.Response
}
var file_proto_meeting_room_proto_depIdxs = []int32{
	1, // 0: meeting.RoomService.GetRooms:input_type -> meeting.ReqGetRooms
	2, // 1: meeting.RoomService.GetRoom:input_type -> meeting.ReqGetRoom
	3, // 2: meeting.RoomService.CreateRoom:input_type -> meeting.ReqCreateRoom
	4, // 3: meeting.RoomService.UpdateRoom:input_type -> meeting.ReqUpdateRoom
	5, // 4: meeting.RoomService.DeleteRoom:input_type -> meeting.ReqDeleteRoom
	6, // 5: meeting.RoomService.GetRooms:output_type -> response.Response
	6, // 6: meeting.RoomService.GetRoom:output_type -> response.Response
	6, // 7: meeting.RoomService.CreateRoom:output_type -> response.Response
	6, // 8: meeting.RoomService.UpdateRoom:output_type -> response.Response
	6, // 9: meeting.RoomService.DeleteRoom:output_type -> response.Response
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_meeting_room_proto_init() }
func file_proto_meeting_room_proto_init() {
	if File_proto_meeting_room_proto != nil {
		return
	}
	file_proto_response_response_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_meeting_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meeting_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetRooms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meeting_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meeting_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqCreateRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meeting_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUpdateRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_meeting_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqDeleteRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_meeting_room_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Room_Status)(nil),
	}
	file_proto_meeting_room_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ReqGetRooms_Status)(nil),
	}
	file_proto_meeting_room_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ReqCreateRoom_Status)(nil),
	}
	file_proto_meeting_room_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*ReqUpdateRoom_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_meeting_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_meeting_room_proto_goTypes,
		DependencyIndexes: file_proto_meeting_room_proto_depIdxs,
		MessageInfos:      file_proto_meeting_room_proto_msgTypes,
	}.Build()
	File_proto_meeting_room_proto = out.File
	file_proto_meeting_room_proto_rawDesc = nil
	file_proto_meeting_room_proto_goTypes = nil
	file_proto_meeting_room_proto_depIdxs = nil
}
